// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateAndStoreEditsForTimeline(arg1, arg2, arg3) {
  return window['go']['main']['App']['CalculateAndStoreEditsForTimeline'](arg1, arg2, arg3);
}

export function CloseApp() {
  return window['go']['main']['App']['CloseApp']();
}

export function DetectSilences(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['DetectSilences'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetGoServerPort() {
  return window['go']['main']['App']['GetGoServerPort']();
}

export function GetOrDetectSilencesWithCache(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['GetOrDetectSilencesWithCache'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function GetOrGenerateWaveformWithCache(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['GetOrGenerateWaveformWithCache'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function GetProjectDataPayloadType() {
  return window['go']['main']['App']['GetProjectDataPayloadType']();
}

export function GetPythonReadyStatus() {
  return window['go']['main']['App']['GetPythonReadyStatus']();
}

export function GetWaveform(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['GetWaveform'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function LaunchHttpServer(arg1) {
  return window['go']['main']['App']['LaunchHttpServer'](arg1);
}

export function LaunchPythonBackend(arg1, arg2) {
  return window['go']['main']['App']['LaunchPythonBackend'](arg1, arg2);
}

export function MakeFinalTimeline(arg1, arg2) {
  return window['go']['main']['App']['MakeFinalTimeline'](arg1, arg2);
}

export function ProcessWavToLinearPeaks(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ProcessWavToLinearPeaks'](arg1, arg2, arg3, arg4);
}

export function ProcessWavToLogarithmicPeaks(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ProcessWavToLogarithmicPeaks'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ResolveBinaryPath(arg1) {
  return window['go']['main']['App']['ResolveBinaryPath'](arg1);
}

export function RunPythonScriptWithArgs(arg1) {
  return window['go']['main']['App']['RunPythonScriptWithArgs'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SendCommandToPython(arg1, arg2) {
  return window['go']['main']['App']['SendCommandToPython'](arg1, arg2);
}

export function SyncWithDavinci() {
  return window['go']['main']['App']['SyncWithDavinci']();
}
