// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateAndStoreEditsForTimeline(arg1, arg2, arg3) {
  return window['go']['main']['App']['CalculateAndStoreEditsForTimeline'](arg1, arg2, arg3);
}

export function CloseApp() {
  return window['go']['main']['App']['CloseApp']();
}

export function DetectSilences(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['DetectSilences'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function DownloadFFmpeg() {
  return window['go']['main']['App']['DownloadFFmpeg']();
}

export function ExecuteAndTrackMixdown(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteAndTrackMixdown'](arg1, arg2, arg3);
}

export function GetCurrentConversionProgress() {
  return window['go']['main']['App']['GetCurrentConversionProgress']();
}

export function GetFFmpegStatus() {
  return window['go']['main']['App']['GetFFmpegStatus']();
}

export function GetGoServerPort() {
  return window['go']['main']['App']['GetGoServerPort']();
}

export function GetOrDetectSilencesWithCache(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['GetOrDetectSilencesWithCache'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function GetOrGenerateWaveformWithCache(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['GetOrGenerateWaveformWithCache'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function GetProjectDataPayloadType() {
  return window['go']['main']['App']['GetProjectDataPayloadType']();
}

export function GetPythonReadyStatus() {
  return window['go']['main']['App']['GetPythonReadyStatus']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetWaveform(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['GetWaveform'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function LaunchHttpServer() {
  return window['go']['main']['App']['LaunchHttpServer']();
}

export function LaunchPythonBackend(arg1, arg2) {
  return window['go']['main']['App']['LaunchPythonBackend'](arg1, arg2);
}

export function MakeFinalTimeline(arg1, arg2) {
  return window['go']['main']['App']['MakeFinalTimeline'](arg1, arg2);
}

export function MixdownCompoundClips(arg1) {
  return window['go']['main']['App']['MixdownCompoundClips'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function ProcessProjectAudio(arg1) {
  return window['go']['main']['App']['ProcessProjectAudio'](arg1);
}

export function ProcessWavToLinearPeaks(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ProcessWavToLinearPeaks'](arg1, arg2, arg3, arg4);
}

export function ProcessWavToLogarithmicPeaks(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ProcessWavToLogarithmicPeaks'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ResolveBinaryPath(arg1) {
  return window['go']['main']['App']['ResolveBinaryPath'](arg1);
}

export function RunPythonScriptWithArgs(arg1) {
  return window['go']['main']['App']['RunPythonScriptWithArgs'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SendCommandToPython(arg1, arg2) {
  return window['go']['main']['App']['SendCommandToPython'](arg1, arg2);
}

export function SetDavinciPlayhead(arg1) {
  return window['go']['main']['App']['SetDavinciPlayhead'](arg1);
}

export function SetWindowAlwaysOnTop(arg1) {
  return window['go']['main']['App']['SetWindowAlwaysOnTop'](arg1);
}

export function StandardizeAudioToWav(arg1, arg2, arg3) {
  return window['go']['main']['App']['StandardizeAudioToWav'](arg1, arg2, arg3);
}

export function SyncWithDavinci() {
  return window['go']['main']['App']['SyncWithDavinci']();
}

export function WaitForFile(arg1) {
  return window['go']['main']['App']['WaitForFile'](arg1);
}
