// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseApp() {
  return window['go']['main']['App']['CloseApp']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetLogarithmicWaveform(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetLogarithmicWaveform'](arg1, arg2, arg3);
}

export function GetOrDetectSilencesWithCache(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetOrDetectSilencesWithCache'](arg1, arg2, arg3, arg4, arg5);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RunPythonScriptWithArgs(arg1) {
  return window['go']['main']['App']['RunPythonScriptWithArgs'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}
