// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CalculateAndStoreEditsForTimeline(arg1:main.ProjectDataPayload,arg2:boolean):Promise<main.ProjectDataPayload>;

export function CloseApp():Promise<void>;

export function DetectSilences(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<Array<main.SilencePeriod>>;

export function GetConfig():Promise<Record<string, any>>;

export function GetGoServerPort():Promise<number>;

export function GetLogarithmicWaveform(arg1:string,arg2:number,arg3:number):Promise<main.PrecomputedWaveformData>;

export function GetOrDetectSilencesWithCache(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<Array<main.SilencePeriod>>;

export function GetOrGenerateWaveformWithCache(arg1:string,arg2:number,arg3:number,arg4:number):Promise<main.PrecomputedWaveformData>;

export function GetProjectDataPayloadType():Promise<main.ProjectDataPayload>;

export function GetPythonReadyStatus():Promise<boolean>;

export function LaunchHttpServer(arg1:any):Promise<void>;

export function LaunchPythonBackend(arg1:number,arg2:number):Promise<void>;

export function MakeFinalTimeline(arg1:main.ProjectDataPayload):Promise<string>;

export function ProcessWavToLogarithmicPeaks(arg1:string,arg2:number,arg3:number,arg4:number):Promise<main.PrecomputedWaveformData>;

export function RunPythonScriptWithArgs(arg1:Array<string>):Promise<void>;

export function SaveConfig(arg1:Record<string, any>):Promise<void>;

export function SendCommandToPython(arg1:string,arg2:Record<string, any>):Promise<main.PythonCommandResponse>;

export function SyncWithDavinci():Promise<main.PythonCommandResponse>;
