// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseApp():Promise<void>;

export function GetConfig():Promise<Record<string, any>>;

export function Greet(arg1:string):Promise<string>;

export function RunPythonScriptWithArgs(arg1:Array<string>):Promise<void>;

export function SaveConfig(arg1:Record<string, any>):Promise<void>;
