// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloseApp():Promise<void>;

export function GetAudioServerPort():Promise<number>;

export function GetConfig():Promise<Record<string, any>>;

export function GetLogarithmicWaveform(arg1:string,arg2:number,arg3:number):Promise<main.PrecomputedWaveformData>;

export function GetOrDetectSilencesWithCache(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<Array<main.SilencePeriod>>;

export function Greet(arg1:string):Promise<string>;

export function RunPythonScriptWithArgs(arg1:Array<string>):Promise<void>;

export function SaveConfig(arg1:Record<string, any>):Promise<void>;
