name: Build and optionally make Release

on:
  push:
    branches:
      - '**'
    tags:
      - '*'

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux/amd64
            ext: ''
            label: linux
          - os: windows-latest
            platform: windows/amd64
            ext: .exe
            label: windows
          - os: macos-latest
            platform: darwin/universal
            ext: ''
            label: macos

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r python-backend/requirements.txt
          python -m pip install pyinstaller

      - name: Build Python backend
        run: |
          pyinstaller python-backend/src/HushCut.py --name python_backend -y
          mkdir -p build/bin
          mkdir -p build/bin/python_backend
          cp dist/python_backend/python_backend${{ matrix.ext }} build/bin/python_backend/python_backend${{ matrix.ext }}
          if [ -d dist/python_backend/_internal ]; then
            cp -r dist/python_backend/_internal build/bin/python_backend/
          fi
          rm -rf dist build/python_backend

      - name: Copy Lua script
        run: cp python-backend/src/HushCut.lua build/bin/

      - name: Install pnpm
        run: npm install -g pnpm

      - name: make public_key files
        run: |
          mkdir -p secrets
          echo "${{ secrets.LICENSE_PUBLIC_KEY }}" > secrets/public_key.pem

      - name: Build Wails App
        uses: dAppServer/wails-build-action@6f01580fdf9e01042bcf2ebe288a934e0d6eb4e2
        with:
          build-name: HushCut
          build-platform: ${{ matrix.platform }}
          package: false
      
      # - name: MacOS download gon for code signing and app notarization
      #   if: matrix.label == 'macos'
      #   run: |
      #     brew install Bearer/tap/gon

      - name: delete python_backend
        run: |
          rm -rf build/bin/python_backend

      - name: Add macOS Resources folder and cleanup
        if: matrix.label == 'macos'
        run: |
          RESOURCE_DIR="build/bin/HushCut.app/Contents/Resources"
          mkdir -p "$RESOURCE_DIR"
          rm -f build/bin/HushCut.app.zip
          rm -f build/bin/HushCut.pkg


      - name: Import Code-Signing Certificates for macOS
        if: matrix.label == 'macos'
        uses: Apple-Actions/import-codesign-certs@v3
        with:
          # The certificates in a PKCS12 file encoded as a base64 string
          p12-file-base64: "${{ secrets.APPLE_DEVELOPER_CERTIFICATE_P12_BASE64 }}"
          # The password used to import the PKCS12 file.
          p12-password: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_PASSWORD }}
      - name: Sign our macOS binary
        if: matrix.label == 'macos'
        env:
          AC_USERNAME: ${{ secrets.APPLE_ID_USERNAME }}
          AC_PASSWORD: ${{ secrets.APPLE_ID_APP_SPECIFIC_PASSWORD }}
        run: |
          echo "Signing Package"
          gon -log-level=info ./code-signing/gon-sign.json
      
      - name: Zip bin folder
        if: startsWith(github.ref, 'refs/tags/') && matrix.label != 'macos'
        run: |
          cd build/bin
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            powershell -Command "Compress-Archive -Path ./* -DestinationPath ../../HushCut-${{ github.ref_name }}-${{ matrix.label }}.zip"
          else
            zip -r ../../HushCut-${{ github.ref_name }}-${{ matrix.label }}.zip .
          fi
      
      - name: Get Dropbox access token
        if: startsWith(github.ref, 'refs/tags/')
        id: dropbox
        run: |
          ACCESS_TOKEN=$(curl -s -X POST https://api.dropbox.com/oauth2/token \
            -u "${{ secrets.DROPBOX_KEY }}:${{ secrets.DROPBOX_SECRET }}" \
            -d grant_type=refresh_token \
            -d refresh_token="${{ secrets.DROPBOX_REFRESH_TOKEN }}" \
            | jq -r '.access_token')
          echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV

      - name: Upload to Dropbox
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          FILENAME="HushCut-${{ github.ref_name }}-${{ matrix.label }}.zip"
          echo "Uploading $FILENAME to Dropbox..."
          curl -X POST https://content.dropboxapi.com/2/files/upload \
            --header "Authorization: Bearer $ACCESS_TOKEN" \
            --header "Dropbox-API-Arg: {\"path\": \"/releases/$FILENAME\",\"mode\": \"add\",\"autorename\": true,\"mute\": false}" \
            --header "Content-Type: application/octet-stream" \
            --data-binary @"$FILENAME"

      # - name: Upload artifact
      #   if: startsWith(github.ref, 'refs/tags/')
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: HushCut-${{ github.ref_name }}-${{ matrix.label }}
      #     path: HushCut-${{ github.ref_name }}-${{ matrix.label }}.zip

  # upload-release-assets:
  #   env:
  #     IS_TAG: ${{ startsWith(github.ref, 'refs/tags/') }}
  #   if: startsWith(github.ref, 'refs/tags/')
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Download all artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         path: artifacts
  #         merge-multiple: true

  #     - name: Display downloaded files
  #       run: ls -R artifacts

  #     - name: Get short-lived access token
  #       id: dropbox
  #       run: |
  #         ACCESS_TOKEN=$(curl -s -X POST https://api.dropbox.com/oauth2/token \
  #           -u "${{ secrets.DROPBOX_KEY }}:${{ secrets.DROPBOX_SECRET }}" \
  #           -d grant_type=refresh_token \
  #           -d refresh_token="${{ secrets.DROPBOX_REFRESH_TOKEN }}" \
  #           | jq -r '.access_token')
  #         echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV

  #     - name: Upload to Dropbox
  #       run: |
  #         for f in artifacts/*.zip; do
  #           FILENAME=$(basename "$f")
  #           echo "Uploading $f to Dropbox..."
  #           curl -X POST https://content.dropboxapi.com/2/files/upload \
  #             --header "Authorization: Bearer $ACCESS_TOKEN" \
  #             --header "Dropbox-API-Arg: {\"path\": \"/releases/$FILENAME\",\"mode\": \"add\",\"autorename\": true,\"mute\": false}" \
  #             --header "Content-Type: application/octet-stream" \
  #             --data-binary @"$f"
  #         done
