name: Release Build (Wails + PyInstaller)

on:
  push:
    tags:
      - '*'

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux/amd64
            ext: ''
          - os: windows-latest
            platform: windows/amd64
            ext: .exe
          - os: macos-latest
            platform: darwin/universal
            ext: ''

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python deps
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -r python-backend/requirements.txt
          pip install pyinstaller

      - name: Build Python backend
        run: |
          pyinstaller python-backend/main.spec -y
          mkdir -p build/bin
          cp dist/main/main${{ matrix.ext }} build/bin/python_backend${{ matrix.ext }}
          if [ -d dist/main/_internal ]; then
            cp -r dist/main/_internal build/bin/
          fi
          rm -rf dist build/main
        shell: bash

      - name: Build Wails frontend
        uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: wailsApp
          build-platform: ${{ matrix.platform }}
          package: false
          go-version: '1.20'

      - name: Upload release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}-build
          path: build/bin/
